# All 545 unique employees (RWSIPL576 deduplicated to first occurrence)
# Format: (employee_code, name, branch, department, designation)
EMPLOYEES = [
    ("DIR", "ABHIJEET SIR", "Maharashtra", "Others", "MD And CEO"),
    ("RWS_CIO", "Akbar Kamal", "Maharashtra", "Projects", "Chief Information Officer"),
    ("RWSIPL007", "Vikas Patil", "Maharashtra", "EC", "Regional Manager"),
    ("RWSIPL013", "Sachin Mool", "Maharashtra", "Solar", "Senior Manager"),
    ("RWSIPL030", "Satyadeo Giri", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL031", "Prabhakar Dehankar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL032", "Shailendra Gautam", "Maharashtra", "EC", "Site Supervisor"),
    ("RWSIPL033", "Rohit Ade", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL034", "Punaram Chouksey", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL047", "Mukesh Panchalwar", "Maharashtra", "EC", "Site Supervisor"),
    ("RWSIPL048", "Pravin Behare", "Maharashtra", "Liaisoning", "MANAGER"),
    ("RWSIPL053", "Dhanraj Masram", "Maharashtra", "Projects", "PLUMBER"),
    ("RWSIPL055", "Uttam Adkane", "Maharashtra", "HR And Admin", "DRIVER"),
    ("RWSIPL081", "Ashok Kumar Sharma", "Rajasthan", "Solar", "Sr Vice President"),
    ("RWSIPL111", "Avaneesh Pattarkine", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL133", "Dheeraj Borkar", "Maharashtra", "Civil", "MANAGER"),
    ("RWSIPL138", "Shashikant Jha", "Bihar", "Projects", "VICE PRESIDENT"),
    ("RWSIPL139", "Surya Prakash Pathak", "Bihar", "Projects", "MANAGER"),
    ("RWSIPL143", "Abhimanyu Singh", "Bihar", "Projects", "Project Executive"),
    ("RWSIPL149", "Kumar Tarun", "Bihar", "Projects", "MANAGER"),
    ("RWSIPL155", "Abhijit Mitra", "Kolkatta_WB", "Projects", "Regional Manager"),
    ("RWSIPL164", "Vaibhav Puntambekar", "Maharashtra", "EC", "MANAGER"),
    ("RWSIPL172", "Pravin Wankhede", "Maharashtra", "HR And Admin", "Office Assistant"),
    ("RWSIPL196", "Nilesh Wasnik", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL202", "Hardeep Rahangdale", "Chattisgarh", "Projects", "MANAGER"),
    ("RWSIPL203", "Arvind Lanjewar", "Maharashtra", "EC", "Regional Manager"),
    ("RWSIPL209", "Prasenjit Saha", "Kolkatta_WB", "Projects", "Project Engineer"),
    ("RWSIPL224", "Sudhakar Ganpatrao Dehare", "Maharashtra", "Purchase", "ASSISTANT MANAGER"),
    ("RWSIPL233", "Bhupesh Ashokrao Mogarkar", "Maharashtra", "Purchase", "ASSISTANT MANAGER"),
    ("RWSIPL236", "Ankush Ramesh Malviya", "Maharashtra", "IoT Energy", "Project Engineer"),
    ("RWSIPL245", "Shubham Mundale", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL246", "Vikash Sharma", "Madhya Pradesh", "Projects", "Site Engineer"),
    ("RWSIPL248", "Abhay Keskar", "Rajasthan", "Solar", "Accounts Manager"),
    ("RWSIPL252", "Bhoopendra Pal", "Maharashtra", "EC", "Project Engineer"),
    ("RWSIPL254", "Pravin Kumar Singh", "Bihar", "Projects", "Sr_Supervisor"),
    ("RWSIPL255", "Anil Kumar", "Jharkhand", "Stores", "Stores Executive"),
    ("RWSIPL256", "Ravi kant Vajpai", "Bihar", "Projects", "Project Executive"),
    ("RWSIPL257", "Vikash Kumar", "Bihar", "Projects", "WTP Mechanic"),
    ("RWSIPL259", "Rabish Kumar Singh", "Bihar", "Stores", "Store Manager"),
    ("RWSIPL264", "Danish Alam", "Bihar", "Projects", "ASSISTANT MANAGER OAndM"),
    ("RWSIPL265", "Indranil Biswas", "Kolkatta_WB", "Projects", "Project Engineer"),
    ("RWSIPL266", "Rani Jha", "Jharkhand", "Projects", "MANAGER"),
    ("RWSIPL268", "Ajit Kumar", "Jharkhand", "Civil", "Site Engineer"),
    ("RWSIPL271", "Rinku Sharma Bhardwaj", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL272", "N Md Irshad", "Maharashtra", "Projects", "ASST Project Coordinator"),
    ("RWSIPL275", "Biswajit Das", "Kolkatta_WB", "Accounts And Finance", "Site Accountant"),
    ("RWSIPL276", "Abhilash Abhinav", "Jharkhand", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL278", "Ashok Kumar", "Jharkhand", "Projects", "Project Executive"),
    ("RWSIPL282", "Arvind Nagpure", "Madhya Pradesh", "Projects", "Project Incharge"),
    ("RWSIPL285", "Arvind Choubey", "Maharashtra", "Projects", "Store Incharge"),
    ("RWSIPL287", "Rakesh Ade", "Chattisgarh", "Projects", "Civil Engineer"),
    ("RWSIPL294", "Narayan Sharma", "Rajasthan", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL295", "Mukesh Sharma", "Rajasthan", "Stores", "MANAGER"),
    ("RWSIPL323", "Pritam Shankarrao Balpande", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL332", "Keshank Makode", "Maharashtra", "Projects", "Project Engineer"),
    ("RWSIPL354", "Piyush Kalambe", "Maharashtra", "EC", "Executive"),
    ("RWSIPL360", "Shyam Balkrishna Bhattbhatt", "Maharashtra", "Accounts And Finance", "CHIEF FINANCE OFFICER"),
    ("RWSIPL374", "Pranjal Kumar", "Bihar", "Projects", "Project Incharge cum Project Manager"),
    ("RWSIPL376", "Rakesh Shrivas", "Maharashtra", "Accounts And Finance", "Accounts Manager"),
    ("RWSIPL377", "Vinesh Nashine", "Maharashtra", "Purchase", "Chief General Manager"),
    ("RWSIPL378", "Viraj Paunikar", "Maharashtra", "EC", "ELECTRICIAN"),
    ("RWSIPL379", "Gopal Joshi", "Rajasthan", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL381", "Abhishek Sharma", "Rajasthan", "Solar", "Site Accountant"),
    ("RWSIPL387", "Vishal Raj", "Jharkhand", "Projects", "Manager Coordination"),
    ("RWSIPL388", "Abhay Maheshgauri", "Maharashtra", "Purchase", "ASSISTANT MANAGER"),
    ("RWSIPL389", "Anil Jibhakate", "Maharashtra", "EC", "Manager Coordination"),
    ("RWSIPL391", "Aparna Maskar", "Maharashtra", "Accounts And Finance", "Sr Executive"),
    ("RWSIPL395", "Saurabhi Randive", "Maharashtra", "IoT Water", "Sr Executive"),
    ("RWSIPL396", "Ravi Sen", "Maharashtra", "EC", "Senior Manager"),
    ("RWSIPL398", "Nitin Chaskar", "Maharashtra", "Marketing", "HEAD BUSINESS DEVELOPMENT"),
    ("RWSIPL407", "Yadnhik Patil", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL409", "Sneha Guhe", "Maharashtra", "EC", "Executive"),
    ("RWSIPL410", "Kailash Hiwarare", "Maharashtra", "HR And Admin", "Office Assistant"),
    ("RWSIPL413", "SUDARSHAN KHARABE", "Maharashtra", "EC", "Project Coordinator"),
    ("RWSIPL419", "DEEPAK SUKHDANE", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL425", "Harish Parate", "Maharashtra", "EC", "GM PROJECTS"),
    ("RWSIPL427", "Pratibha Thote", "Maharashtra", "Tender", "EXECUTIVE TENDER"),
    ("RWSIPL429", "FAIZAL SHEIKH", "Maharashtra", "EC", "Engineer"),
    ("RWSIPL430", "FOOLCHAND AHIRWAR", "Maharashtra", "IoT Energy", "VICE PRESIDENT"),
    ("RWSIPL431", "ASHWINI DEOGADE", "Maharashtra", "HR And Admin", "Sr Executive"),
    ("RWSIPL433", "HEMRAJ SHARMA", "Rajasthan", "Projects", "Project Engineer"),
    ("RWSIPL434", "RAKESH SHARMA", "Rajasthan", "Projects", "Project Engineer"),
    ("RWSIPL435", "AJAY KUMAR JOSHI", "Rajasthan", "Projects", "Project Engineer"),
    ("RWSIPL436", "NARENDRA KUMAR KEER", "Maharashtra", "IoT Water", "Project Engineer"),
    ("RWSIPL437", "Gopesh Sharma", "Maharashtra", "IoT Water", "Sr Engineer"),
    ("RWSIPL438", "Shahidbeg Ashikbeg Mirza", "Maharashtra", "EC", "Project Engineer"),
    ("RWSIPL440", "SACHIN URKUDE", "Maharashtra", "IoT Energy", "ASSISTANT MANAGER"),
    ("RWSIPL441", "Subodh Kamble", "Maharashtra", "IoT Energy", "ASSISTANT MANAGER"),
    ("RWSIPL442", "Pushkar Prasad Ashtikar", "Maharashtra", "Projects", "MANAGER"),
    ("RWSIPL443", "Kamlesh Sukhadeoji Meshram", "Maharashtra", "Stores", "Stores Executive"),
    ("RWSIPL445", "Praful Ninawe", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL446", "Kalpesh Selokar", "Maharashtra", "Projects", "Project Coordinator"),
    ("RWSIPL453", "SANJAY NAYAK", "Maharashtra", "Purchase", "ASSISTANT MANAGER"),
    ("RWSIPL454", "VISHAL MORE", "Maharashtra", "IoT Water", "ASSISTANT MANAGER"),
    ("RWSIPL456", "PRADEEP VYAS", "Rajasthan", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL458", "Avinash Mohite", "Maharashtra", "IoT Water", "Sr Manager"),
    ("RWSIPL461", "ANIKET HINGE", "Maharashtra", "Marketing CSR", "Executive"),
    ("RWSIPL462", "Sandip Istape", "Maharashtra", "IoT Energy", "General Manager"),
    ("RWSIPL463", "YUSUF AHAMAD", "Rajasthan", "Projects", "MANAGER"),
    ("RWSIPL464", "Anmol Luhadia", "Rajasthan", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL465", "KAILAS BORADE", "Maharashtra", "EC", "Deputy Manager"),
    ("RWSIPL466", "DNYANESHWAR MEGHUNDE", "Maharashtra", "EC", "Deputy Manager"),
    ("RWSIPL468", "CHANDRAKANT PATIL", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL469", "NITEEN SONAWANE", "Maharashtra", "IoT Water", "Project Engineer"),
    ("RWSIPL470", "RAVINDRA GADE", "Maharashtra", "EC", "Project Engineer"),
    ("RWSIPL473", "SAURABH LOHAKARE", "Maharashtra", "IoT Energy", "Sr Data Analyst"),
    ("RWSIPL474", "Sandeep Sagdeo", "Maharashtra", "Projects", "Regional Manager"),
    ("RWSIPL476", "Ravi Satpute", "Maharashtra", "EC", "MANAGER"),
    ("RWSIPL477", "Keshav Sharma", "Rajasthan", "Projects", "MANAGER"),
    ("RWSIPL479", "AMIT AHUJA", "Maharashtra", "Company Secretary", "Company Secretary And Compliance Officer"),
    ("RWSIPL480", "SANOJ KUMAR THAKRE", "Madhya Pradesh", "EC", "Accountant"),
    ("RWSIPL481", "RAMRAJYA CHOUKSEY", "Chattisgarh", "Projects", "SUPERVISOR"),
    ("RWSIPL484", "DURGESH NAGPAL", "Rajasthan", "Projects", "MANAGER"),
    ("RWSIPL485", "Shraddha Bhattbhatt", "Maharashtra", "HR And Admin", "Executive"),
    ("RWSIPL487", "Ganesh Fender", "Maharashtra", "IoT Energy", "Project Coordinator"),
    ("RWSIPL489", "Priya Sharma", "Rajasthan", "Projects", "Executive"),
    ("RWSIPL490", "Bhagwan Patil", "Maharashtra", "Projects", "Store Keeper"),
    ("RWSIPL493", "Meenakshi Sharma", "Maharashtra", "HR And Admin", "EA to Director And Administration"),
    ("RWSIPL495", "Rohit Waghmare", "Maharashtra", "Purchase", "Sr Executive"),
    ("RWSIPL498", "Bharti Thakur", "Maharashtra", "Accounts And Finance", "Sr Executive"),
    ("RWSIPL500", "Mrunal Dhoble", "Maharashtra", "Solar", "Regional Manager"),
    ("RWSIPL502", "Girdhari Lal Meena", "Madhya Pradesh", "Solar", "Project Engineer"),
    ("RWSIPL503", "Dilkhush Meena", "Rajasthan", "Projects", "Engineer"),
    ("RWSIPL507", "Rahul Dhole", "Maharashtra", "Solar", "Regional Coordinator"),
    ("RWSIPL508", "Santosh Kumar", "Rajasthan", "Projects", "TECHNICIAN"),
    ("RWSIPL510", "Shankar B. Dhengale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL511", "Pravin A. Bagde", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("RWSIPL512", "Vishnudas P. Kannake", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL513", "Sunil P.Ijamankar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL514", "D.V.GHONGADE", "Maharashtra", "EC", "Store Incharge"),
    ("RWSIPL515", "Umesh N. Nannaware", "Maharashtra", "Projects", "ELECTRICIAN"),
    ("RWSIPL518", "Nishant Khobragade", "Maharashtra", "EC", "TECHNICIAN"),
    ("RWSIPL519", "Manohar Ramteke", "Maharashtra", "EC", "TECHNICIAN"),
    ("RWSIPL520", "Pranay Bagde", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL524", "Gouri Kumawat", "Rajasthan", "Solar", "Business Development Manager"),
    ("RWSIPL526", "Prathmesh Vaidya", "Maharashtra", "EC", "Executive"),
    ("RWSIPL530", "Ranjeet Singh", "Rajasthan", "Projects", "TECHNICIAN"),
    ("RWSIPL531", "Vikash Chand", "Rajasthan", "Projects", "TECHNICIAN"),
    ("RWSIPL533", "Rushikesh Niwal", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL534", "Aniket Mahure", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL536", "Suraj Patdevte", "Maharashtra", "EC", "TECHNICIAN"),
    ("RWSIPL537", "Satish Warkade", "Maharashtra", "EC", "DRIVER"),
    ("RWSIPL538", "Shubham Narekar", "Maharashtra", "Accounts And Finance", "Sr Executive"),
    ("RWSIPL541", "Ishant Merkhed", "Maharashtra", "Accounts And Finance", "Sr Executive"),
    ("RWSIPL543", "ABHISHEK GAIKWAD", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL544", "Akshay Mehar", "Maharashtra", "Projects", "Helper"),
    ("RWSIPL547", "SANJAY ARUN BHUTKAR", "Maharashtra", "IoT Energy", "Regional Manager"),
    ("RWSIPL548", "RITU KUMARI", "Rajasthan", "Operations", "Executive"),
    ("RWSIPL549", "DARSHAN SUNIL DALAL", "Maharashtra", "Solar", "Sr Manager"),
    ("RWSIPL550", "KAUSHIK GHOSH", "Maharashtra", "Solar", "MANAGER"),
    ("RWSIPL552", "VIJAY MADHAV BOINWAD", "Maharashtra", "Projects", "MANAGER"),
    ("RWSIPL553", "ASHISH HARIDASJI RAUT", "Maharashtra", "IoT Energy", "ASSISTANT MANAGER"),
    ("RWSIPL555", "Kiran Ingle", "Maharashtra", "IoT Energy", "ASSISTANT MANAGER"),
    ("RWSIPL560", "Md. Sahzad Alam", "Rajasthan", "Projects", "Sr Engineer"),
    ("RWSIPL561", "Brajesh Kant Jha", "Bihar", "Projects", "MANAGER"),
    ("RWSIPL562", "Pavankumar Pawar", "Maharashtra", "IoT Energy", "MANAGER"),
    ("RWSIPL563", "Rakesh Ranjan", "Jharkhand", "Projects", "Executive"),
    ("RWSIPL564", "Brajesh Kumar Rathore", "Maharashtra", "IoT Water", "Assistant General Manager"),
    ("RWSIPL566", "Rakesh Kumar", "Maharashtra", "IoT Energy", "MANAGER"),
    ("RWSIPL569", "Shashank Nikose", "Maharashtra", "IoT Energy", "Site Engineer"),
    ("RWSIPL570", "Jai Dutt Sharma", "Maharashtra", "Technical", "General Manager"),
    ("RWSIPL571", "Tauhid Alam", "Maharashtra", "IoT Energy", "Sr Engineer"),
    ("RWSIPL572", "Shajiya Banu", "Rajasthan", "Projects", "MIS Executive"),
    ("RWSIPL574", "Kaustubh Gaikwad", "Maharashtra", "Stores", "Sr Executive"),
    ("RWSIPL576", "Prasanna Papalkar", "Maharashtra", "Accounts And Finance", "MANAGER"),
    ("RWSIPL577", "Rushikesh Bhise", "Maharashtra", "Accounts And Finance", "Executive"),
    ("RWSIPL579", "Manoj Kumar Kumawat", "Maharashtra", "Stores", "Executive"),
    ("RWSIPL580", "Amod Nirmal", "Maharashtra", "HR And Admin", "Sr Executive"),
    ("RWSIPL584", "GAJANAN TARDE", "Maharashtra", "EC", "TECHNICIAN"),
    ("RWSIPL585", "VAIBHAV WAKODE", "Maharashtra", "EC", "TECHNICIAN"),
    ("RWSIPL588", "BHAVESH B. WAGHOSKAR", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL591", "Kiran Barku Shinde", "Maharashtra", "EC", "ASSISTANT MANAGER"),
    ("RWSIPL592", "BIKASH SINGH", "Bihar", "Projects", "SUPERVISOR"),
    ("RWSIPL593", "KANHAIYALAL", "Bihar", "Projects", "PLUMBER"),
    ("RWSIPL594", "Pankaj Kumar Singh", "Jharkhand", "Projects", "DRIVER"),
    ("RWSIPL596", "RAJESH YADAV", "Bihar", "Projects", "PLUMBER"),
    ("RWSIPL597", "Krishna kamal kumar", "Jharkhand", "Execution Maintenance", "SUPERVISOR"),
    ("RWSIPL598", "RAHUL RANJAN", "Bihar", "Projects", "Project Coordinator"),
    ("RWSIPL599", "PAPPU RAM", "Bihar", "Projects", "ELECTRICIAN"),
    ("RWSIPL600", "KUNDAN KUMAR SINGH", "Bihar", "Projects", "SUPERVISOR"),
    ("RWSIPL601", "PRAFULL NARAYAN BHASKAR", "Bihar", "Projects", "SUPERVISOR"),
    ("RWSIPL602", "Vijay kumar", "Jharkhand", "Execution Maintenance", "TECHNICIAN"),
    ("RWSIPL603", "Santosh Kumar Yadav", "Jharkhand", "Execution Maintenance", "TECHNICIAN"),
    ("RWSIPL604", "Pravin Mate", "Maharashtra", "Quality Control", "MANAGER"),
    ("RWSIPL606", "Dolendra Chachane", "Maharashtra", "Projects", "Executive"),
    ("RWSIPL607", "C P Vijay", "Madhya Pradesh", "Solar", "Sr GM_Projects"),
    ("RWSIPL609", "Mukesh Kumar", "Rajasthan", "Projects", "Engineer"),
    ("RWSIPL611", "Rajesh Kumar Meena", "Rajasthan", "Projects", "Engineer"),
    ("RWSIPL612", "Deepak Wagh", "Maharashtra", "Projects", "Project Executive"),
    ("RWSIPL613", "Arpit Pandit", "Maharashtra", "IoT Energy", "Project Engineer"),
    ("RWSIPL617", "Sanjay Fender", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL618", "Sadik Khan", "Maharashtra", "IoT Energy", "SUPERVISOR"),
    ("RWSIPL622", "Pravin Thakre", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL626", "Dhananjay Surjuse", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL627", "Chetan Surjuse", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL629", "Viccky Bisne", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL630", "Komal Thakre", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL631", "Pooja Sawalikar", "Maharashtra", "Purchase", "Sr Executive"),
    ("RWSIPL632", "Shivani Chauhan", "Maharashtra", "Projects", "Sr Executive"),
    ("RWSIPL633", "Abhishek Anturkar", "Maharashtra", "IoT Water", "Data Analyst"),
    ("RWSIPL634", "Mayuri Nasare", "Maharashtra", "Solar", "Data Entry Opt"),
    ("RWSIPL635", "Meenal Mohod", "Maharashtra", "Accounts And Finance", "Executive"),
    ("RWSIPL637", "Sugat Thoolkar", "Maharashtra", "HR And Admin", "DRIVER"),
    ("RWSIPL640", "Rohan Shingade", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL643", "Amol Bachhav", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL646", "Amol Gedam", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL647", "Saurabh Likhar", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL648", "Akshay Khandare", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL649", "Mohit Sharma", "Rajasthan", "Warehouse", "Executive"),
    ("RWSIPL650", "Mahesh Umarkar", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL652", "Mithun Jibhkate", "Maharashtra", "IoT Energy", "Configuration Engineer"),
    ("RWSIPL656", "Nikhil Murodiya", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL658", "Rameshwar Jengathe", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL661", "TARUN SARATE", "Maharashtra", "EC", "Project Coordinator"),
    ("RWSIPL664", "Abhishek Chavan", "Maharashtra", "Projects", "Executive"),
    ("RWSIPL665", "Yogesh Ubarhande", "Maharashtra", "Solar", "Regional Coordinator"),
    ("RWSIPL666", "Rahul Kapgate", "Maharashtra", "Solar", "Regional Coordinator"),
    ("RWSIPL668", "Kartik Dhobale", "Maharashtra", "IoT Water", "Executive"),
    ("RWSIPL669", "Kunal Sonawane", "Maharashtra", "IoT Water", "Executive"),
    ("RWSIPL670", "Shivam Singh", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL673", "Shubham Nagtilak", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL676", "Amol Khandare", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL679", "Pranay Kumar", "Maharashtra", "Solar", "Senior Manager"),
    ("RWSIPL680", "Dhriti Bagla", "Maharashtra", "Projects", "Executive"),
    ("RWSIPL681", "Sanket Zade", "Maharashtra", "Projects", "Executive"),
    ("RWSIPL682", "Sheshrao Mahajan", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL683", "Ashutosh Jadhav", "Maharashtra", "IoT Energy", "SCADA Engineer"),
    ("RWSIPL684", "Pankaj Wagh", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL686", "Shivank Bansod", "Maharashtra", "IoT Energy", "SCADA Engineer"),
    ("RWSIPL688", "Vivek Mahajan", "Maharashtra", "IoT Energy", "SCADA Engineer"),
    ("RWSIPL691", "Nilesh Vasudev Bhavsar", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL693", "Vrushabh Chahande", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL694", "Vaibhav Shambharkar", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL695", "Ankit Chindaliya", "Maharashtra", "Marketing", "MANAGER"),
    ("RWSIPL696", "Yogesh Zodekar", "Maharashtra", "HR And Admin", "DRIVER"),
    ("RWSIPL697", "Devanand Nandedkar", "Maharashtra", "Projects", "Accountant"),
    ("RWSIPL698", "Krishna Nimje", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL699", "Aman Shrivas", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL701", "Raj Raidas", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL702", "Liladhar Pathare", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL703", "Nakul Urkude", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL705", "Harshad Nandanwar", "Maharashtra", "Projects", "Store Incharge"),
    ("RWSIPL706", "Mahesh Jadhav", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL707", "Yogiraj Popat Hadge", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL708", "Sumit Ravindra Bhavsar", "Maharashtra", "IoT Energy", "ASSISTANT MANAGER"),
    ("RWSIPL711", "Sham Shah", "Maharashtra", "Solar", "Senior Manager"),
    ("RWSIPL712", "Saurabh Chougule", "Maharashtra", "HR And Admin", "Executive"),
    ("RWSIPL714", "Manish Ojha", "Maharashtra", "IoT Water", "General Manager"),
    ("RWSIPL718", "Piyush Mishra", "Maharashtra", "Projects", "Service Engineer"),
    ("RWSIPL719", "Sanjay Choudhary", "Rajasthan", "Business Development", "General Manager"),
    ("RWSIPL721", "Pankaj Papadkar", "Maharashtra", "Accounts And Finance", "Senior Manager"),
    ("RWSIPL723", "Akhilesh Awate", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL725", "Rupesh Bokde", "Maharashtra", "Accounts And Finance", "General Manager"),
    ("RWSIPL726", "Prashant Sharma", "Maharashtra", "Projects", "Assistant General Manager"),
    ("RWSIPL729", "Adarsh Aharwar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL731", "Sayyad Bakhtiyar", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL732", "Deepak Kumar Sharma", "Rajasthan", "Projects", "MANAGER"),
    ("RWSIPL733", "Roshan Bachhav", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL735", "Sumit Basewar", "Maharashtra", "Accounts And Finance", "Executive"),
    ("RWSIPL736", "Sonu Ahirwar", "Maharashtra", "Projects", "Project Coordinator"),
    ("RWSIPL737", "Pradeep Nagle", "Madhya Pradesh", "Projects", "Sr Billing Executive"),
    ("RWSIPL738", "Radhika Dorle", "Maharashtra", "Projects", ""),
    ("RWSIPL739", "Pravin Gadekar", "Maharashtra", "Projects", "Trainee Engineer"),
    ("RWSIPL740", "MD. Akhtar", "Maharashtra", "Projects", "Engineer"),
    ("RWSIPL742", "Ashlesh Chopde", "Maharashtra", "Projects", "Engineer"),
    ("RWSIPL744", "Priyanka Somkuwar", "Maharashtra", "HR And Admin", "Sr Executive"),
    ("RWSIPL745", "Sachin Patil", "Maharashtra", "Projects", "ASSISTANT MANAGER"),
    ("RWSIPL748", "Bhavika Kishor Gore", "Maharashtra", "Projects", "Executive"),
    ("RWSIPL750", "Mrunal Chimote", "Maharashtra", "Projects", "Engineer"),
    ("RWSIPL751", "ANIL RAGHUNATH HINGAVE", "Maharashtra", "Accounts And Finance", "Executive"),
    ("RWSIPL753", "Gaurav Tike", "Maharashtra", "IoT Energy", "Sr Engineer"),
    ("RWSIPL754", "Shreyash Urkude", "Maharashtra", "IoT Energy", "Configuration Engineer"),
    ("RWSIPL755", "Shatrughna Barik", "Maharashtra", "HR And Admin", "Office Boy"),
    ("RWSIPL756", "Shital Lichade", "Maharashtra", "IoT Energy", "MANAGER"),
    ("RWSIPL757", "Dhammadhwaj Gaikwad", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("RWSIPL758", "Harshal Patil", "Maharashtra", "Projects", "Site Supervisor"),
    ("RWSIPL759", "Ritik Meshram", "Maharashtra", "IoT Water", "TECHNICIAN"),
    ("RWSIPL760", "Chetan Arun Kute", "Maharashtra", "Projects", "TECHNICIAN"),
    ("RWSIPL761", "HARSHVARDHAN DAYARAM AHIRE", "Maharashtra", "IoT Energy", "Executive"),
    ("RWSIPL763", "Deepak Sanjay Patil", "Maharashtra", "IoT Energy", "Site Engineer"),
    ("RWSIPL764", "Roshni Foolchand Ahirwar", "Maharashtra", "IoT Water", "MANAGER"),
    ("RWSIPL765", "Aman Kumar Singh", "Maharashtra", "Solar", "Regional Manager"),
    ("RWSIPL766", "Yash Gawali", "Maharashtra", "IoT Energy", "Executive"),
    ("RWSIPL767", "SANDEEP RAMSINGH SATILANJEWAR", "Maharashtra", "Projects", "Project Engineer"),
    ("RWSIPL768", "Shubham Adke", "Maharashtra", "IoT Water", "TECHNICIAN"),
    ("RWSIPL769", "Manish Kumar Verma", "Maharashtra", "Projects", "Project Management Officer"),
    ("RWSIPL770", "Keshav Kumar Singh", "Jharkhand", "Solar", "Project Coordinator"),
    ("RWSIPL771", "Sidharth Donde", "Maharashtra", "Projects", "Manager Electrical n Electronics"),
    ("RWSIPL772", "Vinayak Raju Rathod", "Maharashtra", "IoT Energy", "MANAGER"),
    ("RWSIPL773", "Santosh Moreshwar Divekar", "Maharashtra", "Stores", "Manager-Inventory Control"),
    ("RWSIPL774", "Sharda Kishor Somkuwar", "Maharashtra", "Solar", "Executive"),
    ("RWSIPL776", "Sankhdeep Goswami", "Maharashtra", "Projects", "MANAGER"),
    ("RWSIPL777", "Rajan Gupta", "Maharashtra", "Solar", "Project Executive"),
    ("RWSIPL778", "Sanjay Kadam", "Maharashtra", "Projects", "General Manager"),
    ("RWSIPL779", "Rajeev Ranjan Mishra", "Maharashtra", "Projects", "VICE PRESIDENT"),
    ("RWSIPL780", "Amit Lahanuji Nanhe", "Maharashtra", "Solar", "MIS Executive"),
    ("RWSIPL781", "Arti Changhode", "Maharashtra", "Solar - Rooftop", "Design and Proposal Engineer"),
    ("RWSIPL782", "Manoj Shankar Hande", "Maharashtra", "PROPOSAL AND TENDERING", "Sr Engineer"),
    ("RWSIPL783", "Sourabh Dineshrao Sakhare", "Maharashtra", "Solar - Rooftop", "Engineer"),
    ("RWSIPL784", "Polawar Sudheer", "Maharashtra", "PROPOSAL AND TENDERING", "Senior General Manager"),
    ("RWSIPL785", "Hariom Choubey", "Madhya Pradesh", "Solar - Rooftop", "Regional Manager"),
    ("RWSIPL786", "Madhav Chhatrapati Pawar", "Maharashtra", "Solar - Rooftop", "Sr Manager"),
    ("RWSIPL787", "Vikas Gajananrao Sadafale", "Maharashtra", "IoT Energy", "Engineer"),
    ("RWSIPL788", "Nishant Kumar", "Bihar", "Solar - Rooftop", "ASSISTANT MANAGER"),
    ("RWSIPL789", "Anand Vilas Radke", "Maharashtra", "HR And Admin", "DEPUTY GENERAL MANAGER"),
    ("RWSIPL790", "Mayur Sumant Indurkar", "Maharashtra", "Stores", "ASSISTANT MANAGER"),
    ("TRWSIPL010", "Ratan Lal", "Rajasthan", "Projects", "TECHNICIAN"),
    ("TRWSIPL015", "Pawan Kumar Panchal", "Rajasthan", "Projects", "SUPERVISOR"),
    ("TRWSIPL017", "Virendra Kumar Suman", "Rajasthan", "Projects", "SUPERVISOR"),
    ("TRWSIPL054", "JITENDRA PASWAN", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL060", "SHIVNANDAN KUMAR SINGH", "Bihar", "Projects", "SUPERVISOR"),
    ("TRWSIPL065", "NANDLAL PANDIT", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL068", "Pawan Paswan", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL070", "Mukesh Kumar", "Bihar", "Projects", "TECHNICIAN"),
    ("TRWSIPL071", "Madhusudan Mandal", "Bihar", "Projects", "TECHNICIAN"),
    ("TRWSIPL072", "Manoj Kumar", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL073", "Chamaklal Mandal", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL074", "Jyotish Kumar", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL075", "Sunil Ravidas", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL078", "Nandan Kumar Singh", "Bihar", "Projects", "SUPERVISOR"),
    ("TRWSIPL080", "Amardeep Kumar", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL081", "Akhilesh Kumar Paswan", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL088", "Suraj kumar Soni", "Jharkhand", "Execution and Maintenance", "TECHNICIAN"),
    ("TRWSIPL184", "Ajay Rajendra Baviskar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL201", "KALIRAM DATTU PATIL", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL202", "Ramsingh Meena", "Rajasthan", "Projects", "SUPERVISOR"),
    ("TRWSIPL260", "Aamin Yasin Tadavi", "Maharashtra", "Projects", "Stores Executive"),
    ("TRWSIPL264", "Nandan Mandal", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL269", "Ravindra Namdev Pondhekar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL270", "Vaibhav Raghunath Dinkar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL278", "Sagar Radhkishan Mal", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL282", "Sunil Wasudeo Nandagawali", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL300", "Sunil Parasharam Pawar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL318", "Indas Somnath Wagh", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL320", "Gaurav Subhash Wagh", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL336", "Sachin Vasant Lakhan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL367", "Suchit Bhalchandra Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL368", "Alpesh Yashwant Dinkar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL388", "Yoganand Mandal", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL410", "MAHESHWAR PUNDLIK NIKURE", "Maharashtra", "Projects", "DRIVER"),
    ("TRWSIPL421", "Mangesh Ramesh bhondi", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL425", "Sagar Sheshrao Kullarkar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL433", "Nanigopal Manoranjan Sikdar", "Kolkatta_WB", "Projects", "SUPERVISOR"),
    ("TRWSIPL435", "DEEPAK SOREN", "Bihar", "Projects", "STORE SECURITY GUARD"),
    ("TRWSIPL436", "BASUKI KUMAR YADAV", "Bihar", "Projects", "ELECTRICIAN"),
    ("TRWSIPL439", "RAKESH SINGH", "Bihar", "Projects", "Helper"),
    ("TRWSIPL440", "RAKESH KUMAR MANDAL", "Bihar", "Projects", "Helper"),
    ("TRWSIPL443", "Chhabi Nohar Goswami", "Chattisgarh", "Projects", "TECHNICIAN"),
    ("TRWSIPL444", "Tarun Rajendra Patel", "Chattisgarh", "Projects", "TECHNICIAN"),
    ("TRWSIPL445", "Kamal Shatrugan sahu", "Chattisgarh", "Projects", "TECHNICIAN"),
    ("TRWSIPL446", "Dinesh Harilal Vishwakarma", "Chattisgarh", "Projects", "TECHNICIAN"),
    ("TRWSIPL447", "Ravsaheb Pandurang Kobarane", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL449", "MRITUNJAY SATYADEV GIRI", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL455", "PANKAJ HEMRAJ GOUR", "Maharashtra", "Projects", "DRIVER"),
    ("TRWSIPL458", "KUMENDRA MUNNALAL BISEN", "Chattisgarh", "Projects", "SUPERVISOR"),
    ("TRWSIPL462", "BIRENDRA PASWAN", "Maharashtra", "Projects", "PLUMBER"),
    ("TRWSIPL463", "SUJAY BADAAM PASWAN", "Maharashtra", "Projects", "PLUMBER"),
    ("TRWSIPL464", "ABHISHEK BAGHEL", "Madhya Pradesh", "Projects", "SUPERVISOR"),
    ("TRWSIPL465", "SACHENDRA DWARKA PRAJAPATI", "Chattisgarh", "Projects", "SUPERVISOR"),
    ("TRWSIPL466", "ABHISHEK DILIP MATHURI", "Madhya Pradesh", "Projects", "PLUMBER"),
    ("TRWSIPL467", "GULSHAN VISHNUDEV RAY", "Madhya Pradesh", "Projects", "PLUMBER"),
    ("TRWSIPL470", "PARASRAM SHYAMLAL RAJAK", "Madhya Pradesh", "Projects", "SUPERVISOR"),
    ("TRWSIPL471", "SHIVKUMAR MALVI", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL473", "DHANSU BISANT BADAIVANSH", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL474", "Nandlal Yadav", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL475", "BUNTY TIKARAM BODALKHANDE", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL477", "AKASH DINKAR TAYDE", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL481", "BHUSHAN PRABHAKAR YEVLE", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL483", "SUKALURAM CHALLA", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL484", "MANOJ LAMTURE", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL487", "Saurabh Devidas Dudhakohar", "Maharashtra", "Projects", "DRIVER"),
    ("TRWSIPL489", "Gopal Sajjan Rathod", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL492", "DILIP PRALHAD DIWAN", "Maharashtra", "Projects", "Project Executive"),
    ("TRWSIPL494", "VAIBHAV VIJAY NIWAL", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL495", "SUDHAKAR GOPALRAO GHODE", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL500", "DIPAK VADHANKAR", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL503", "Aanand Chakrapani", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL505", "Dhanjay Bawane", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL507", "Sagar Koli", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL508", "Bharti Ghadle", "Maharashtra", "Projects", "Telecaller"),
    ("TRWSIPL523", "Mahesh Mahlu Sargade", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL524", "Ganesh Vastare", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL525", "Abasaheb Bhand", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL526", "Kamlesh Nagar", "Rajasthan", "Projects", "Office Assistant"),
    ("TRWSIPL531", "Kalpesh Pawar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL533", "Omkar Bhagirath jadhav", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL535", "Swapnil Suryakant Kale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL540", "Shivkala Uikey", "Maharashtra", "Projects", "Telecaller"),
    ("TRWSIPL541", "Ghanshyam Kumar Yadav", "Bihar", "Projects", "Helper"),
    ("TRWSIPL543", "Sameer Hiraman Gaikwad", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL546", "Tushar Dhansing Nimbalkar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL553", "Nitish Kumar", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL554", "Pappu Kumar Sharma", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL564", "Bhushan Kadambande", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL565", "Vithoba Ravde", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL569", "Kiran Sandhan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL575", "Dinesh Balai", "Rajasthan", "Projects", "DRIVER"),
    ("TRWSIPL578", "Vithoba Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL581", "Vijay Das", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL587", "Sanjay Anand Das", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL599", "Narendra Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL603", "Chaitanya Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL604", "Hritik Kashinath Lakhan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL606", "Menkam Longchang", "Arunachal Pradesh", "Projects", "TECHNICIAN"),
    ("TRWSIPL614", "Dhanraj Randhave", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL615", "Shrikant Kale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL619", "Sukalu Marmadiya", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL620", "Akash Thakre", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL622", "Girraj Meena", "Rajasthan", "Projects", "TECHNICIAN"),
    ("TRWSIPL623", "Pintu Kumar", "Jharkhand", "Projects", "TECHNICIAN"),
    ("TRWSIPL624", "Bholaram Chandrawanshi", "Jharkhand", "Projects", "TECHNICIAN"),
    ("TRWSIPL625", "Subhash Yadav", "Bihar", "Projects", "TECHNICIAN"),
    ("TRWSIPL628", "Ranjan Kumar", "Bihar", "Projects", "PLUMBER"),
    ("TRWSIPL630", "Sahil Rahangdale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL631", "Rohit Gautam", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL634", "Mahesh Kolse", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL639", "Mantu Kumar", "Rajasthan", "Projects", "TECHNICIAN"),
    ("TRWSIPL641", "Subhash Kumar", "Rajasthan", "Projects", "TECHNICIAN"),
    ("TRWSIPL642", "Ashwini Deore", "Maharashtra", "Projects", "Data Entry Opt"),
    ("TRWSIPL646", "Vipin Kumar Tiwari", "Jharkhand", "Projects", "TECHNICIAN"),
    ("TRWSIPL647", "Deepak Kumar Chandravanshi", "Jharkhand", "Projects", "Store Keeper"),
    ("TRWSIPL652", "Priyanshu Hatwar", "Maharashtra", "Projects", "Data Entry Opt"),
    ("TRWSIPL653", "Devadatta Thankar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL657", "Abhishek Zoting", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL658", "Ravindra Waghade", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL662", "Vighnesh Waghoskar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL664", "Mikhayal Gudekar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL666", "Abdul Rehan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL667", "Shadnam Ejaj Patel", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL676", "Karan Kodape", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL682", "Rohit Sharma", "Maharashtra", "Projects", "Site Supervisor"),
    ("TRWSIPL683", "Bharatkumar Rahangdale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL684", "Pranay Papadkar", "Maharashtra", "Projects", "Executive"),
    ("TRWSIPL687", "Gokul Kandu Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL688", "Dhananjay Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL691", "Ashok Wagh", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL693", "Nilesh Vishwas", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL694", "Amrut Roy", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL697", "Akash Tayade", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL698", "Nikhil More", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL701", "Akashbhai Tayade", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL707", "Gorakh Patil", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL710", "Pallavi Shende", "Maharashtra", "Projects", "Telecaller"),
    ("TRWSIPL712", "Mahavir Nigude", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL713", "Niraj Dolaskar", "Maharashtra", "Projects", "Engineer"),
    ("TRWSIPL715", "Avinash Sutar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL716", "Virendra Baghele", "Maharashtra", "IoT Water", ""),
    ("TRWSIPL717", "Omkar Pandhare", "Maharashtra", "Projects", "Executive"),
    ("TRWSIPL719", "Shridhar Kale", "Maharashtra", "Projects", "Executive"),
    ("TRWSIPL720", "Devidas Gangurde", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL721", "Subhash chougule", "Maharashtra", "Projects", ""),
    ("TRWSIPL723", "Bhavesh Shinde", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL725", "Rohit Shigwan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL726", "Ramkishor Rajjak", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL727", "Nilesh Koli", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL728", "Nilesh Bendre", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL730", "Jay Prakash", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL731", "Madan Pusam", "Maharashtra", "IoT Water", "TECHNICIAN"),
    ("TRWSIPL732", "Manohar Shrisath", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL733", "Sonali Dalvi", "Maharashtra", "Projects", "Back office Assistant"),
    ("TRWSIPL735", "Babaji Suryawanshi", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL737", "Ayush Jadhav", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL739", "Murlidhar Gurchal", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL740", "Sachin More", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL741", "Digambar Rathod", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL742", "Manoj Chavan", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL743", "Ganesh Pawar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL744", "Pratik Rajad", "Maharashtra", "Projects", "Surveyor"),
    ("TRWSIPL745", "Amol Uike", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL746", "Amol Tadas", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL747", "Bhalchandra Dinkar", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL748", "Nandkishor Malvi", "Maharashtra", "Projects", "Site Supervisor"),
    ("TRWSIPL749", "Ambadas Shirsath", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL750", "Kishor kajale", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL752", "Chetan Shende", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL753", "Mangesh tagad", "Maharashtra", "Projects", "DRIVER"),
    ("TRWSIPL754", "Amol Savalikar", "Maharashtra", "IoT Water", "Engineer"),
    ("TRWSIPL755", "Shivraj Kottewar", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("TRWSIPL760", "Ajay Raju Marathe", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL762", "Kiran Vikas Napte", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL763", "Ganesh Bhandare", "Maharashtra", "IoT Water", "Site Engineer"),
    ("TRWSIPL765", "Raksha Rewatkar", "Maharashtra", "IoT Water", "MIS Executive"),
    ("TRWSIPL768", "Ganesh Gaikwad", "Maharashtra", "Projects", "Project Engineer"),
    ("TRWSIPL771", "Pramod Padavi", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL772", "Jitendra Jadhav", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL773", "Sandip Nathe", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL774", "Mininath Jadhav", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL777", "Saurabh Kedari", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL779", "Dhanraj Shete", "Maharashtra", "Projects", "Service Engineer"),
    ("TRWSIPL781", "Tushar Kisanrao Bhone", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL782", "Umesh Patil", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL784", "Ankush Pendam", "Maharashtra", "Projects", "TECHNICIAN"),
    ("TRWSIPL785", "Jatin dhadse", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("TRWSIPL786", "Roman Bhilavekar", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("TRWSIPL787", "Amit Nisal", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL788", "Ajay Somnath Wagh", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL789", "Kailas Tayade", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL790", "Pravin Kochure", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL791", "Gulab Kalu Gaikwad", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL792", "Avinash Keram", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL795", "Gopal Bandu Jadhav", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL796", "Suryabhan Surwade", "Maharashtra", "EC", "DRIVER"),
    ("TRWSIPL797", "Rahul Pimpale", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("TRWSIPL798", "Chandrashekhar Raut", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL799", "Anushri Borkar", "Maharashtra", "Solar", "Telecaller"),
    ("TRWSIPL800", "Nayana Nishedh Waghmare", "Maharashtra", "Solar", "Telecaller"),
    ("TRWSIPL801", "Subhash Kumar Choure", "Bihar", "Projects", "Store Keeper"),
    ("TRWSIPL804", "Avinash Wadaskar", "Maharashtra", "Energy", "TRAINEE"),
    ("TRWSIPL805", "Jitendra Hanwate", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL806", "Manish Parteti", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL807", "Aniket Pardhi", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL809", "Onkar Narayan Tarvade", "Maharashtra", "IoT Water", "Site Supervisor"),
    ("TRWSIPL810", "Ayush Rajendra Wasu", "Maharashtra", "Energy", "Project Engineer"),
    ("TRWSIPL811", "Siraj Parman Tadavi", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL812", "Husen Tadavi", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL813", "Rahul bhimrav Chavan", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL814", "Pradeep Harsing Chavhan", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL815", "Ganesh Shankar Zavare", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL816", "Samir Pardhi", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL817", "Pradeep Patil", "Maharashtra", "IoT Water", "TECHNICIAN"),
    ("TRWSIPL818", "Yash Vitthal Kawadkar", "Maharashtra", "Solar", "MIS Executive"),
    ("TRWSIPL820", "Shrikant Patil", "Maharashtra", "EC", "Store Incharge"),
    ("TRWSIPL821", "Ritesh Chaudhari", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL822", "Jagdish Bhamare", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL823", "Devidas Tumbade", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL824", "Shubham Gunwant Bobade", "Maharashtra", "IoT Energy", "TECHNICIAN"),
    ("TRWSIPL825", "Manisha Rangari", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL826", "Sarika Maske", "Maharashtra", "Projects", "Helper"),
    ("TRWSIPL827", "Shivani kamble", "Maharashtra", "Energy", "TRAINEE"),
    ("TRWSIPL828", "Shahid Rafik Sheikh", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL829", "KRUSHNA PAWAR", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL830", "Sandip Sangale", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL831", "Payal Rajgire", "Maharashtra", "Energy", "MIS Executive"),
    ("TRWSIPL832", "Tarachand Pawara", "Maharashtra", "IoT Energy", "Site Supervisor"),
    ("TRWSIPL833", "Sham Bhoyar", "Maharashtra", "Energy", "TECHNICIAN"),
    ("TRWSIPL834", "Dev Jaikalyani", "Maharashtra", "Projects", "TRAINEE"),
    ("TRWSIPL835", "Jayant Thakre", "Maharashtra", "Solar", "Executive"),
    ("TRWSIPL836", "Manthan Padir", "Maharashtra", "Solar", "Executive"),
    ("TRWSIPL837", "Vimlesh Patle", "Maharashtra", "Solar - Rooftop", "TECHNICIAN"),
    ("TRWSIPL838", "Rohit Jadhav", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL839", "Ansh Gupta", "Maharashtra", "Projects", "TRAINEE"),
    ("TRWSIPL840", "Sarvesh Veginwar", "Maharashtra", "Projects", "TRAINEE"),
    ("TRWSIPL841", "Digambar Madavi", "Maharashtra", "EC", "TECHNICIAN"),
    ("TRWSIPL842", "Rahul Shingate", "Maharashtra", "EC", "Surveyor"),
    ("TRWSIPL843", "Kundan Kumar", "Bihar", "Projects", "Sr_Supervisor"),
]
